[build]
command = "npm install" # Adjust this based on your project's build setup
publish = "public"      # The folder to publish

[dev]
command = "npm run start" # Your development server start command
